// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_2-rUSXlRevGpdDuNNC2RU6B-SVy9TzU',
    appId: '1:357909312615:web:c4364471dc0569fae390c2',
    messagingSenderId: '357909312615',
    projectId: 'time-logger-3912c',
    authDomain: 'time-logger-3912c.firebaseapp.com',
    storageBucket: 'time-logger-3912c.appspot.com',
    measurementId: 'G-48ZH0MKFG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzDQEArC2gUPrilF6Z3_aHl78ThVQqsGA',
    appId: '1:357909312615:android:3c588153e4dd83a2e390c2',
    messagingSenderId: '357909312615',
    projectId: 'time-logger-3912c',
    storageBucket: 'time-logger-3912c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Tux4jMtbCIxXUArf8_jmZKi1k0t5YIs',
    appId: '1:357909312615:ios:419a47615f00a249e390c2',
    messagingSenderId: '357909312615',
    projectId: 'time-logger-3912c',
    storageBucket: 'time-logger-3912c.appspot.com',
    iosBundleId: 'com.example.timeLogger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4Tux4jMtbCIxXUArf8_jmZKi1k0t5YIs',
    appId: '1:357909312615:ios:f7716be9efd4bf42e390c2',
    messagingSenderId: '357909312615',
    projectId: 'time-logger-3912c',
    storageBucket: 'time-logger-3912c.appspot.com',
    iosBundleId: 'com.example.timeLogger.RunnerTests',
  );
}
